import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar"; // Import the Navbar component
import Footer from "../components/Footer"; //Import the footer component

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Add metadata including favicon
export const metadata = {
  title: "Hey, I'm Vidushi",
  description: "Generated by hard work",
  icons: {
    icon: "/favicon/favicon.ico", // Path to favicon
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Link to the favicon */}
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="stylesheet" href="/globals.css" />
        </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Add the Navbar component here */}
        <div className="navbar-margin">
          <Navbar />
        </div>

        {children}
        <Footer/>
      </body>
    </html>
  );
}
