import localFont from "next/font/local";
import "./globals.css";
import RootLayout from "../components/RootLayout"; // Import the Client version

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// ✅ Export metadata (Server Component)
export const metadata = {
  title: "Hey, I'm Vidushi",
  description: "Generated by hard work",
  icons: {
    icon: "/favicon/favicon.ico",
  },
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
