import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar"; // Import the Navbar component
import Footer from "../components/Footer"; //Import the footer component

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Hey, I'm Vidushi",
  description: "Generated by hard work",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Add the Navbar component here */}
        <div className="navbar-margin">
          <Navbar />
        </div>

        {children}
        <Footer/>
      </body>
    </html>
  );
}
